import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';
import { cn } from '@/lib/utils';
import './globals.css';

const fontNotoSansJP = Noto_Sans_JP({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Post Writer',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        // cn関数を使うことで、クラスの重複を避ける
        className={cn(
          'bg-background antialiased min-h-screen',
          fontNotoSansJP.className
        )}
      >
        {children}
      </body>
    </html>
  );
}
